# Docker compose file for GoLang API with postgresql database
version: "3.1"
services:
  api:
    build: .
    ports:
      - "8888:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
